version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:16-alpine
    container_name: tradelog_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-tradelog}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Backend API (Go)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tradelog_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - PORT=8080
      # Connect to the 'postgres' service defined above
      - DB_URL=postgres://admin:secret@localhost:5432/tradelog?sslmode=disable
      - JWT_SECRET=this_is_my_secret_key_for_the_assignment
      - JWT_REFRESH_SECRET=this_is_my_refresh_secret_key_for_the_assignment
      - JWT_EXPIRATION_HOURS=1
      - ADMIN_SECRET=make_me_an_admin_please
    depends_on:
      - postgres

  # 3. The Frontend (Next.js)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: tradelog_web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: